### ISSUE TITLE
Invalid call to lazypipe().pipe(): argument is not a function

### ISSUE THREAD

**Issue by SkiftCreative** [OverZealous/lazypipe#19]
Here is my gulpfile:

```
'use strict';

var browserSync = require('browser-sync');
var conf = require('./conf');
var gulp = require('gulp');
var gulpif = require('gulp-if');
var lazypipe = require('lazypipe')
var path = require('path');
var rename = require('gulp-rename')
var sourcemaps = require('gulp-sourcemaps')
var uglify = require('gulp-uglify')

var src  = conf.getFiles('assets')('js')
var dest = path.join(conf.paths.static, 'js')

var compressjs = lazypipe()
  .pipe(sourcemaps.init())
  .pipe(uglify())
  .pipe(uglify())
  .pipe(sourcemaps.write())
  .pipe(rename({suffix: '.min'}))
  .pipe(gulp.dest(dest))


function scripts(watch, compress) {
  return gulp.src(src)
    .pipe(gulp.dest(dest))
    .pipe(function() {
      return gulpif(compress, compressjs)
    })
    .pipe(gulpif(watch, browserSync.reload({stream: true})))
}

gulp.task('scripts', function() {
  return scripts(false, false);
});
```

And when I run `gulp scripts` I get the following error:

```
/Users/shawn/www/projects/skiftcreative/skift/app/themes/material/node_modules/lazypipe/index.js:11
			throw new Error("Invalid call to lazypipe().pipe(): argument is not a funct
			      ^
Error: Invalid call to lazypipe().pipe(): argument is not a function.
    Remember not to call stream creation functions directly! e.g.: pipe(foo), not pipe(foo())
    at validateStep (/Users/shawn/www/projects/skiftcreative/skift/app/themes/material/node_modules/lazypipe/index.js:11:10)
    at Function.build.pipe (/Users/shawn/www/projects/skiftcreative/skift/app/themes/material/node_modules/lazypipe/index.js:36:4)
    at Object.<anonymous> (/Users/shawn/www/projects/skiftcreative/skift/app/themes/material/gulp/scripts.js:17:4)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at /Users/shawn/www/projects/skiftcreative/skift/app/themes/material/gulpfile.js:16:5
```

I have read #3 but looking over my code, it looks correct. Basically I want to use `gulp-if` to test if I want to do compression (passed as 'true' in another task). But on this part of the code:

```
var compressjs = lazypipe()
  .pipe(sourcemaps.init())
```

the `.pipe()` method seems to be undefined. looking at all the examples, as well as here https://github.com/robrich/gulp-if#works-great-with-lazypipe

Any idea? Thanks.

**Comment by OverZealous** [comment]
Please read the error message, it explains what you are doing wrong.

**Comment by ghostsquad** [comment]
This response isn't helpful. I just ran into the same issue. It _seems_ as though this error is asking for:

```Coffeescript
coffeeTasks = lazypipe()
  .pipe(coffeelint())
  .pipe(coffeelint.reporter())
  .pipe(coffeelint.reporter('fail'))
  .pipe(sourcemaps.init())
  .pipe(coffee({header: true}))
  .pipe(sourcemaps.write())

gulp.task 'build', ['clean'], ->
  return gulp.src(paths.coffee)
    .pipe(coffeeTasks)  #<<<<<<<<<< no () here
    .pipe(gulp.dest(paths.jsSrcRoot))
```

I've tried with with `coffeeTasks()` and `coffeeTasks` and I get the same error. What's up??

**Comment by OverZealous** [comment]
@ghostsquad 
Seriously?  Take 2s and read the error message:

> Invalid call to lazypipe().pipe(): argument is not a function.
>    Remember not to call stream creation functions directly! e.g.: pipe(foo), not pipe(foo())

It's says, clearly, to use `pipe(foo) not `pipe(foo())`.  Arguments to the pipe creation function can be passed in as additional parameters to the `lazypipe().pipe` function.  [All this is provided as examples within the docs.](https://github.com/OverZealous/lazypipe#using-with-more-complex-function-arguments-such-as-gulp-if).

**Comment by ghostsquad** [comment]
Yep, my bad.. I didn't read it closely enough. :(

Anyways, thanks for the module!!! :)
